// Extended demo data — accounts, properties, contacts, permit links.
// Stored in window.DEMO_DATA_EXTENDED only; does NOT mutate VESTIBULE_DATA.

(function () {
  const ACCOUNTS = [
    { id:'acc-h1', kind:'hotel',      name:'Sydell Hotel Group',       short:'Sydell',
      hq:'1180 Broadway, NYC', locations:14, nyLocations:6, totalRooms:1840,
      relationship:'warm', notes:'Met VP of Design at Boutique Hotel Awards. NoMad + LINE NY both in their portfolio.',
      keyContacts:['c-101','c-102'], openings:3, revenue:92000, won:2,
      brands:['NoMad','LINE Hotel','Freehand'] },
    { id:'acc-h2', kind:'hotel',      name:'Ace Hotel Group',          short:'Ace',
      hq:'20 W 29th St', locations:11, nyLocations:2, totalRooms:1220,
      relationship:'cool', notes:'Cold. Director of Construction unresponsive — try Sister Property at Sister City.',
      keyContacts:['c-103'], openings:2, revenue:0, won:0,
      brands:['Ace','Sister City'] },
    { id:'acc-h3', kind:'hotel',      name:'Standard International',   short:'Standard',
      hq:'444 W 13th St', locations:7, nyLocations:3, totalRooms:740,
      relationship:'warm', notes:'Did vestibule retrofit at Standard East Village 2024. Reference customer.',
      keyContacts:['c-104'], openings:1, revenue:38000, won:1,
      brands:['The Standard','Bunkhouse'] },
    { id:'acc-h4', kind:'hotel',      name:'Pomp Hotels',              short:'Pomp',
      hq:'New York, NY', locations:4, nyLocations:4, totalRooms:520,
      relationship:'hot', notes:'Founder, Adam Heier, has 4 properties opening 2026. Wants every entrance to match.',
      keyContacts:['c-105'], openings:4, revenue:0, won:0,
      brands:['The Camby','The Frederick'] },
    { id:'acc-h5', kind:'hotel',      name:'Hyatt Hospitality NYC',    short:'Hyatt',
      hq:'71 W 35th St', locations:9, nyLocations:5, totalRooms:2280,
      relationship:'cold', notes:'Enterprise. Through-procurement only. Long sales cycle.',
      keyContacts:['c-106'], openings:0, revenue:0, won:0,
      brands:['Andaz','Hyatt Place','Park Hyatt'] },
    { id:'acc-r1', kind:'restaurant', name:'Quality Branded',          short:'Quality',
      hq:'40 W 57th St', locations:9, nyLocations:7, totalRooms:0,
      relationship:'warm', notes:'COO is Alan Stillman\'s son. Smith & Wollensky, Quality Meats, Don Angie style.',
      keyContacts:['c-201'], openings:2, revenue:28000, won:1,
      brands:['Quality Meats','Don Angie','Bad Roman'] },
    { id:'acc-r2', kind:'restaurant', name:'Crafted Hospitality',      short:'Crafted',
      hq:'43 E 19th St', locations:6, nyLocations:5, totalRooms:0,
      relationship:'hot', notes:'Tom\'s ops director called us first. Strong reference. 2 deals closed.',
      keyContacts:['c-202'], openings:3, revenue:41000, won:2,
      brands:['Craft','Colicchio Heritage'] },
    { id:'acc-r3', kind:'restaurant', name:'Major Food Group',         short:'MFG',
      hq:'New York, NY', locations:18, nyLocations:11, totalRooms:0,
      relationship:'cool', notes:'Carbone, Sadelle\'s, Torrisi. Hard to reach. Go through architect (Wu).',
      keyContacts:['c-203'], openings:2, revenue:0, won:0,
      brands:['Carbone','Sadelle\'s','Torrisi','ZZ\'s'] },
    { id:'acc-r4', kind:'restaurant', name:'Frenchette Group',         short:'Frenchette',
      hq:'241 W Broadway', locations:3, nyLocations:3, totalRooms:0,
      relationship:'warm', notes:'Riad Nasr is responsive. Opening 4th location summer.',
      keyContacts:['c-204'], openings:1, revenue:11400, won:1,
      brands:['Frenchette','Le Rock','Le Veau d\'Or'] },
    { id:'acc-r5', kind:'restaurant', name:'Tao Group Hospitality',    short:'Tao Group',
      hq:'440 W 42nd St', locations:21, nyLocations:9, totalRooms:0,
      relationship:'cool', notes:'Enterprise. Procurement-driven. Need RFP.',
      keyContacts:['c-205'], openings:1, revenue:0, won:0,
      brands:['Tao','Lavo','The Highlight Room'] },
    { id:'acc-r6', kind:'restaurant', name:'Andrew Tarlow Group',      short:'Tarlow',
      hq:'178 Broadway, BK', locations:5, nyLocations:5, totalRooms:0,
      relationship:'hot', notes:'Diner, Marlow & Sons, Reynard. BK foundational. Andrew is hands-on.',
      keyContacts:['c-206'], openings:2, revenue:18800, won:1,
      brands:['Diner','Marlow & Sons','Reynard'] },
    { id:'acc-r7', kind:'restaurant', name:'Union Square Hospitality', short:'USHG',
      hq:'24 Union Sq E', locations:15, nyLocations:14, totalRooms:0,
      relationship:'warm', notes:'Danny Meyer org. Met Chief Design Officer at Hospitality Show.',
      keyContacts:['c-207'], openings:2, revenue:22600, won:2,
      brands:['Gramercy Tavern','Union Square Cafe','Shake Shack'] },
  ];

  const PROPERTIES = [
    { id:'pr-1', name:'RFR Holding',          kind:'reit',    portfolio:'72 NYC buildings',           primary:'Aby Rosen',        addresses:['375 Park Ave','980 Madison Ave','530 Madison Ave'],  permits:4, relationship:'warm', notes:'Asset manager Greg Levy handles ground-floor retail tenant improvements.' },
    { id:'pr-2', name:'Vornado Realty',       kind:'reit',    portfolio:'24M sq ft NY office + retail', primary:'Steven Roth',    addresses:['350 Park Ave','One Penn Plaza','Two Penn Plaza'],       permits:3, relationship:'cool', notes:'Through Cushman & Wakefield only.' },
    { id:'pr-3', name:'Brodsky Organization', kind:'private', portfolio:'8,500 NYC residential units', primary:'Daniel Brodsky', addresses:['225 Mulberry St','241 Mulberry St','176 Mulberry St'], permits:6, relationship:'hot',  notes:'Owns much of NoLita ground floor. Three permits across their buildings this month.' },
    { id:'pr-4', name:'Two Trees Management', kind:'private', portfolio:'DUMBO + Williamsburg',        primary:'David Walentas', addresses:['45 Main St','60 Water St','Domino Sugar'],              permits:5, relationship:'warm', notes:'Will introduce you to their tenant-improvement vendors.' },
    { id:'pr-5', name:'Tishman Speyer',       kind:'reit',    portfolio:'Rockefeller Center + 30 sites', primary:'Rob Speyer',  addresses:['Rockefeller Plaza','30 Hudson Yards'],                  permits:2, relationship:'cold', notes:'Procurement gate. Pass for now.' },
    { id:'pr-6', name:'L.A. Petillo & Sons',  kind:'family',  portfolio:'9 mixed-use LES + EV',       primary:'Vincent Petillo',addresses:['127 Stanton St','159 Ludlow St','78 Rivington St'],     permits:4, relationship:'hot',  notes:'Vincent answers his own phone. Buys vestibule before tenant moves in.' },
    { id:'pr-7', name:'Brooklyn Capital LLC', kind:'private', portfolio:'24 storefronts in BK',        primary:'Ari Krasner',    addresses:['461 Court St','298 Smith St','344 Court St'],            permits:4, relationship:'warm', notes:'Wants vestibules pre-installed before showing to tenants — sells the lease faster.' },
    { id:'pr-8', name:'Solil Management',     kind:'family',  portfolio:'200+ NYC retail leases',      primary:'Sol Goldman estate', addresses:['various'],                                           permits:3, relationship:'cool', notes:'Old NY. Hard to reach but huge portfolio.' },
    { id:'pr-9', name:'Hidrock Properties',   kind:'private', portfolio:'24 hotel + retail assets',    primary:'Abie Hidary',    addresses:['various'],                                               permits:2, relationship:'new',  notes:'Hotel-focused. New connection.' },
  ];

  const CONTACTS = [
    { id:'c-101', name:'Andrea Petrich',     title:'VP Design',               org:'Sydell Hotel Group',       kind:'operator',      email:'apetrich@sydell.com',           phone:'(212) 555-0220', relationship:'warm', notes:'2 yr cycle from concept to opening; loops in vestibule at SD.', lastTouch:'2026-05-15', accountId:'acc-h1' },
    { id:'c-102', name:'Marco Innocente',    title:'Director of Construction', org:'Sydell',                  kind:'operator',      email:'marco@sydell.com',              phone:'(917) 555-0221', relationship:'cool', notes:'Loops Andrea — try Andrea direct.', lastTouch:'2026-04-30', accountId:'acc-h1' },
    { id:'c-103', name:'Sasha Pham',         title:'Design Director',          org:'Ace Hotel Group',         kind:'operator',      email:'sasha@acehotelgroup.com',        phone:'(347) 555-0240', relationship:'cool', notes:'Met at Hospitality Design Expo. No follow-up.', lastTouch:'2026-03-12', accountId:'acc-h2' },
    { id:'c-104', name:'Jenna Lyons',        title:'Construction Lead',         org:'Standard Intl',          kind:'operator',      email:'jenna@standardhotels.com',       phone:'(212) 555-0250', relationship:'warm', notes:'Gave us the Standard East Village job. Reference.', lastTouch:'2026-05-08', accountId:'acc-h3' },
    { id:'c-105', name:'Adam Heier',         title:'Founder',                  org:'Pomp Hotels',             kind:'operator',      email:'adam@pomphotels.co',            phone:'(212) 555-0265', relationship:'hot',  notes:'Wants 4 vestibules across 4 hotels. Master spec opportunity.', lastTouch:'2026-05-21', accountId:'acc-h4' },
    { id:'c-106', name:'Robert Tan',         title:'VP NA Construction',       org:'Hyatt Hospitality NYC',   kind:'operator',      email:'rtan@hyatt.com',                phone:'(212) 555-0280', relationship:'cold', notes:'Procurement gates.', lastTouch:'2026-02-19', accountId:'acc-h5' },
    { id:'c-201', name:'Will Stillman',      title:'COO',                      org:'Quality Branded',         kind:'operator',      email:'will@qualitybranded.com',        phone:'(212) 555-0301', relationship:'warm', notes:'Inherited from father Alan. Modernizing portfolio.', lastTouch:'2026-05-11', accountId:'acc-r1' },
    { id:'c-202', name:'Lauren Diehl',       title:'Director of Ops',          org:'Crafted Hospitality',     kind:'operator',      email:'lauren@crafted.co',             phone:'(917) 555-0312', relationship:'hot',  notes:'Reference customer. Will refer.', lastTouch:'2026-05-20', accountId:'acc-r2' },
    { id:'c-203', name:'Mario Carbone',      title:'Partner',                  org:'Major Food Group',        kind:'operator',      email:null, phone:null,                                         relationship:'cold', notes:'Reach via Wu (architect). Go through Riad Nasr instead.', lastTouch:null, accountId:'acc-r3' },
    { id:'c-204', name:'Riad Nasr',          title:'Chef / Partner',           org:'Frenchette Group',        kind:'operator',      email:'r@frenchette.co',               phone:'(646) 555-0330', relationship:'warm', notes:'Responsive on email. Loves the craft angle.', lastTouch:'2026-05-19', accountId:'acc-r4' },
    { id:'c-205', name:'Nicholas DiMartino', title:'VP Development',           org:'Tao Group Hospitality',   kind:'operator',      email:'ndimartino@taogroup.com',        phone:'(212) 555-0340', relationship:'cool', notes:'RFP only.', lastTouch:'2026-04-02', accountId:'acc-r5' },
    { id:'c-206', name:'Andrew Tarlow',      title:'Founder',                  org:'Andrew Tarlow Group',     kind:'operator',      email:'andrew@marlowgroup.co',          phone:'(718) 555-0355', relationship:'hot',  notes:'Hands-on owner. Will pitch peers in BK.', lastTouch:'2026-05-22', accountId:'acc-r6' },
    { id:'c-207', name:'Anya Kallikkadan',   title:'Chief Design Officer',     org:'Union Square Hospitality',kind:'operator',      email:'anya@ushgnyc.com',              phone:'(212) 555-0370', relationship:'warm', notes:'12 openings in pipeline. Standardizing entry design.', lastTouch:'2026-05-12', accountId:'acc-r7' },
    { id:'c-301', name:'Greg Levy',          title:'Asset Manager, Retail',    org:'RFR Holding',             kind:'property',      email:'glevy@rfr.com',                 phone:'(212) 555-0411', relationship:'warm', notes:'Handles ground-floor TI across RFR portfolio.', lastTouch:'2026-05-10', propertyId:'pr-1' },
    { id:'c-302', name:'Vincent Petillo',    title:'Owner',                    org:'L.A. Petillo & Sons',     kind:'property',      email:'vince@petillonyc.com',           phone:'(917) 555-0420', relationship:'hot',  notes:'Answers his own phone. Old NY landlord.', lastTouch:'2026-05-22', propertyId:'pr-6' },
    { id:'c-303', name:'Ari Krasner',        title:'Principal',                org:'Brooklyn Capital LLC',    kind:'property',      email:'ari@bkcap.co',                  phone:'(347) 555-0431', relationship:'warm', notes:'Pre-installs to speed lease-up.', lastTouch:'2026-05-15', propertyId:'pr-7' },
    { id:'c-304', name:'Daniel Brodsky',     title:'Co-Chairman',              org:'Brodsky Organization',    kind:'property',      email:'dbrodsky@brodskynyc.com',        phone:'(212) 555-0444', relationship:'hot',  notes:'NoLita patriarch. Referred by Petillo.', lastTouch:'2026-05-19', propertyId:'pr-3' },
    { id:'c-305', name:'Joyce Mui',          title:'Construction Manager',     org:'Two Trees',               kind:'property',      email:'joyce@twotrees.com',            phone:'(718) 555-0455', relationship:'warm', notes:'DUMBO. Handles tenant fitout vendors.', lastTouch:'2026-05-08', propertyId:'pr-4' },
    { id:'c-401', name:'Jenny Park',         title:'Owner-Operator',           org:'Forsythia Wine Bar',      kind:'operator-solo', email:'jenny@forsythiawine.com',        phone:'(212) 555-0501', relationship:'new',  notes:'Solo operator, first restaurant.', lastTouch:null },
    { id:'c-402', name:'Eddie Huang',        title:'Owner-Operator',           org:'Bar Tonic',               kind:'operator-solo', email:'eddie@bartonic.nyc',            phone:'(212) 555-0511', relationship:'warm', notes:'Repeat opener — Bar Tonic is his third.', lastTouch:'2026-05-17' },
    { id:'c-403', name:'Mei Tanaka',         title:'Owner',                    org:'Sake Bar Rin',            kind:'operator-solo', email:'mei@sakebarrin.co',             phone:'(212) 555-0520', relationship:'cool', notes:'Quiet. Communicate through architect.', lastTouch:null },
    { id:'c-404', name:'Antonio Carmine',    title:'2nd-gen Owner',            org:'Carmine Sons Pizza',      kind:'operator-solo', email:'antonio@carminesons.com',        phone:'(212) 555-0530', relationship:'warm', notes:'Family-owned since 1971. Renovating.', lastTouch:'2026-05-12' },
    { id:'c-501', name:'Kevin Murphy',       title:'Owner',                    org:'Murphy Build NY',         kind:'gc',            email:'kevin@murphybuildny.com',        phone:'(917) 555-0601', relationship:'warm', notes:'GC. Has 6 restaurant builds running now.', lastTouch:'2026-05-19' },
    { id:'c-502', name:'Sergio Romero',      title:'PM',                       org:'Romero Construction',     kind:'gc',            email:'sergio@romeroconstruction.nyc', phone:'(347) 555-0612', relationship:'cool', notes:'Project Manager — pass to him after architect.', lastTouch:'2026-04-25' },
  ];

  const PERMIT_LINKS = {
    'B00781246': { accountId:null,     propertyId:'pr-3' },
    'B00779812': { accountId:null,     propertyId:'pr-6', contactId:'c-402' },
    'B00782104': { accountId:null,     propertyId:'pr-6', contactId:'c-403' },
    'B00780994': { accountId:'acc-r2', propertyId:'pr-4' },
    'B00781877': { accountId:null,     propertyId:'pr-3', contactId:'c-404' },
    'B00782339': { accountId:'acc-r6', propertyId:'pr-7' },
    'B00779441': { accountId:null,     propertyId:'pr-6' },
    'B00782501': { accountId:'acc-r3', propertyId:'pr-3' },
    'B00780012': { accountId:'acc-r4', propertyId:'pr-1' },
    'B00782820': { accountId:'acc-h3', propertyId:null   },
    'B00782188': { accountId:'acc-r7', propertyId:null   },
    'B00782717': { accountId:'acc-r3', propertyId:'pr-6' },
    'B00781400': { accountId:'acc-r4', propertyId:'pr-1' },
    'B00782456': { accountId:'acc-r2', propertyId:null   },
    'B00782604': { accountId:'acc-r6', propertyId:'pr-7' },
    'B00782902': { accountId:null,     propertyId:null   },
    'B00781766': { accountId:'acc-h1', propertyId:null   },
    'B00782255': { accountId:'acc-r3', propertyId:null   },
    'B00782788': { accountId:'acc-h4', propertyId:'pr-3' },
    'B00780333': { accountId:null,     propertyId:null   },
    'B00782144': { accountId:'acc-h3', propertyId:null   },
    'B00779099': { accountId:null,     propertyId:'pr-3' },
    'B00782611': { accountId:null,     propertyId:null   },
    'B00782899': { accountId:'acc-r6', propertyId:'pr-7' },
    'B00782940': { accountId:'acc-h4', propertyId:'pr-3' },
    'B00782955': { accountId:null,     propertyId:'pr-7' },
    'B00782971': { accountId:'acc-r7', propertyId:null   },
    'B00782990': { accountId:'acc-r6', propertyId:null   },
    'B00782612': { accountId:null,     propertyId:'pr-6' },
    'B00781088': { accountId:'acc-r2', propertyId:'pr-7' },
    'B00779733': { accountId:null,     propertyId:'pr-1' },
    'B00779555': { accountId:'acc-h1', propertyId:null   },
    'B00778812': { accountId:'acc-r6', propertyId:null   },
    'B00778622': { accountId:'acc-h3', propertyId:null   },
    'B00778201': { accountId:'acc-r2', propertyId:null   },
    'B00782811': { accountId:null,     propertyId:null   },
    'B00782477': { accountId:'acc-r3', propertyId:null   },
    'B00781999': { accountId:'acc-h4', propertyId:'pr-6' },
    'B00782766': { accountId:null,     propertyId:null   },
    'B00782233': { accountId:null,     propertyId:'pr-3' },
    'B00782321': { accountId:'acc-r1', propertyId:null   },
    'B00782580': { accountId:'acc-r6', propertyId:'pr-7' },
  };

  window.DEMO_DATA_EXTENDED = { ACCOUNTS, PROPERTIES, CONTACTS, PERMIT_LINKS };
})();
